language: scala
git:
  depth: 9999
install:
  - git fetch --tags
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
script:
  - ./bin/runci.sh $CI_TEST
jdk:
  - oraclejdk8
env:
  global:
  - TRAVIS_NODE_VERSION="8"
  matrix:
    - CI_TEST: check
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.11.11
      CI_PUBLISH: true
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.11.11
      CI_SCALA_JS: true
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.12.3
      CI_PUBLISH: true
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.12.3
      CI_SCALA_JS: true

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier
  - target/repos

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
  - rm -rf $HOME/.ivy2/local

after_success:
- "./bin/ci-publish.sh"
