language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package
scala:
  - 2.11.5
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
env:
  global:
   - SCALAMETA_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAMETA_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "OXuy1Hmj9DKB6EvptcS0HYWlUSzFJVGjmuSbjleRRs5ZEH5rl1yJ5mUYxkt0+OJnV+0h/fySJSbncKRbS5oYp8ARS/29oNhUFM+ZMj9N9mi8uKyfZuSbZdWARTTpaO7c65xQo5JKWO63R572gFotrxWagArW6ouLXBfhxYTKKjU="
   - secure: "BrO2yxNBb+e1Qe419sKbR/EaeZX3O3Reqh9octuMRWoZxLb15KxQUQXC55UeByTEueH8CF7YSS6gGWRruClcboUF7KTnj3Y2SKoNya0z6HkLqj/jzPFhFb76MPbTRP+e78GD3RDCb7Yp7GQ+4RD/y1NIdUYT6kPqCuZhTQrwqHo="
