language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
env:
  global:
   - SCALAMETA_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAMETA_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "zQAIM0c3xtM+CYtbFp+G6ONopS8qahaWzvv5hy9OUSp9ZGWd3OzVu33pi0ovOx2D4XKQ3z+Q5sXGFBe6Z3pUshrDv3HsyQ8gzb5z2L06k0YgPCnnAX335Hjgj/4faWr5Pv7mviduDLNnA60ltnAz/J/LonZZK+qXi+VEHaDEtxg="
   - secure: "dkolBbb18yfBAsXn5/AUtrwn6yit55p3ml74kxQMKAV7Yc3R3vqWFDB/jNTskziRFDL5hHPVGxwC7LHXALdfTZUMSYel0SXX3GVl2OaJ9tOFVz+1bX7KM95iGmzEHw59XvT/H+7624E4sy2+vKk+hsM7vhgswQpRliawFR6Mpcc="
