version: '{build}'
os: Windows Server 2012
install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: $ErrorActionPreference = "Continue"
  - ps: scoop bucket add versions
  - ps: $ErrorActionPreference = "Stop"
  - ps: scoop install sbt0.13
environment:
  CI_SCALA_VERSION: 2.12.6
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
build_script:
  - sbt version # dummy step, a build_script step is required by appveyor.
test_script:
  - sbt testsJVM/test # testsJS/test is disabled because of OOM errors
cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
  - C:\Users\appveyor\.coursier
  - C:\Users\appveyor\scoop\cache
  - target\repos
